RD /S /Q "Be.Windows.Forms.HexBox\obj"
RD /S /Q "Be.Windows.Forms.HexBox\bin\Debug"
RD /S /Q "Be.Windows.Forms.HexBox\bin\Release"
RD /S /Q "Be.Windows.Forms.HexBox\bin\x86\Debug"
DEL /Q /F /S "Be.Windows.Forms.HexBox\bin\x86\Release\*.pdb"
RD /S /Q "DareDebuggerWV\obj"
RD /S /Q "DareDebuggerWV\bin\Debug"
RD /S /Q "DareDebuggerWV\bin\Release"
RD /S /Q "DareDebuggerWV\bin\x86\Debug"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.config"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.vshost.*"
RD /S /Q "DTBReaderWV\obj"
RD /S /Q "DTBReaderWV\bin\Debug"
RD /S /Q "DTBReaderWV\bin\Release"
RD /S /Q "DTBReaderWV\bin\x86\Debug"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.config"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.vshost.*"
RD /S /Q "GRFSBackend\obj"
RD /S /Q "GRFSBackend\bin\Debug"
RD /S /Q "GRFSBackend\bin\Release"
RD /S /Q "GRFSBackend\bin\x86\Debug"
DEL /Q /F /S "GRFSBackend\bin\x86\Release\*.pdb"
DEL /Q /F /S "GRFSBackend\bin\x86\Release\*.config"
DEL /Q /F /S "GRFSBackend\bin\x86\Release\*.vshost.*"
DEL /Q /F /S "GRFSBackend\bin\x86\Release\*.txt"
DEL /Q /F /S "GRFSBackend\bin\x86\Release\*.bin"
RD /S /Q "QuazalSharkWV\obj"
RD /S /Q "QuazalSharkWV\bin\Debug"
RD /S /Q "QuazalSharkWV\bin\Release"
RD /S /Q "QuazalSharkWV\bin\x86\Debug"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.config"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.vshost.*"
RD /S /Q "QuazalWV\obj"
RD /S /Q "QuazalWV\bin\Debug"
RD /S /Q "QuazalWV\bin\Release"
RD /S /Q "QuazalWV\bin\x86\Debug"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.config"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.vshost.*"
DEL /Q /F /S "GRFSBackend.sdf"
RD /S /Q "ipch"
streams.exe -s -d
pause